spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacy?createDatabaseIfNotExist=true
    # url: jdbc:postgresql://localhost:5432/pharmacy
    username: root
    password: P1@netMar
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true